name: ReportSystem
version: '1.0'
main: me.reportsystem.reportsystem.ReportSystem
api-version: '1.20'
authors:
  - kaplumbaga
description: Minecraft sunucuları için discord'a report sistemi
commands:
  report:
    description: Bir şikayet bildirin
    usage: /<command> <message>
